$("#link1").click(function(){ $("#hiraganachart").toggle();
});
$("#link2").click(function(){ $("#katakanachart").toggle();
});
$("#link3").click(function(){ $("#kanjichart").toggle();
});
$("#link4").click(function(){ $("#usefulphrases").toggle();
});
$("#link5").click(function(){ $("#culturepart").toggle();
});
